# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataDirectoryWindow(object):
    def setupUi(self, DataDirectoryWindow):
        DataDirectoryWindow.setObjectName("DataDirectoryWindow")
        DataDirectoryWindow.resize(649, 466)
        self.centralwidget = QtWidgets.QWidget(DataDirectoryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 641, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.CopyButton = QtWidgets.QPushButton(self.centralwidget)
        self.CopyButton.setGeometry(QtCore.QRect(490, 200, 93, 28))
        self.CopyButton.setObjectName("CopyButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(450, 240, 181, 121))
        self.textBrowser.setObjectName("textBrowser")
        DataDirectoryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(DataDirectoryWindow)
        QtCore.QMetaObject.connectSlotsByName(DataDirectoryWindow)

    def retranslateUi(self, DataDirectoryWindow):
        _translate = QtCore.QCoreApplication.translate
        DataDirectoryWindow.setWindowTitle(_translate("DataDirectoryWindow", "DATA_DIRECTRY"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DataDirectoryWindow", "Content"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DataDirectoryWindow", "Size"))
        self.CopyButton.setText(_translate("DataDirectoryWindow", "Copy"))
