# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWinDow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 600))
        MainWindow.setMaximumSize(QtCore.QSize(700, 600))
        MainWindow.setBaseSize(QtCore.QSize(300, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 600, 600))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(600, 600))
        self.textBrowser.setMaximumSize(QtCore.QSize(600, 600))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionguanbi = QtWidgets.QAction(MainWindow)
        self.actionguanbi.setObjectName("actionguanbi")
        self.actionIMAGE_DOS_HEADER = QtWidgets.QAction(MainWindow)
        self.actionIMAGE_DOS_HEADER.setObjectName("actionIMAGE_DOS_HEADER")
        self.actionIMAGE_FILE_HEADER = QtWidgets.QAction(MainWindow)
        self.actionIMAGE_FILE_HEADER.setObjectName("actionIMAGE_FILE_HEADER")
        self.actionIMAGE_OPTINAL_HEADER = QtWidgets.QAction(MainWindow)
        self.actionIMAGE_OPTINAL_HEADER.setObjectName("actionIMAGE_OPTINAL_HEADER")
        self.actionIMAGE_DATA_HEADER = QtWidgets.QAction(MainWindow)
        self.actionIMAGE_DATA_HEADER.setObjectName("actionIMAGE_DATA_HEADER")
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionguanbi)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.toolBar.addAction(self.actionIMAGE_DOS_HEADER)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIMAGE_FILE_HEADER)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIMAGE_OPTINAL_HEADER)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionIMAGE_DATA_HEADER)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PETool"))
        self.textBrowser.setHtml(_translate("MainWindow", "提示:请打开要查看的文件"))
        self.menuOpen.setTitle(_translate("MainWindow", "文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "打开"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionguanbi.setText(_translate("MainWindow", "关闭"))
        self.actionguanbi.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionIMAGE_DOS_HEADER.setText(_translate("MainWindow", "DOS_HEADER"))
        self.actionIMAGE_DOS_HEADER.setIconText(_translate("MainWindow", "DOS_HEADER"))
        self.actionIMAGE_DOS_HEADER.setToolTip(_translate("MainWindow", "DOS_HEADER"))
        self.actionIMAGE_FILE_HEADER.setText(_translate("MainWindow", "FILE_HEADER"))
        self.actionIMAGE_OPTINAL_HEADER.setText(_translate("MainWindow", "OPTINAL_HEADER"))
        self.actionIMAGE_DATA_HEADER.setText(_translate("MainWindow", "DATA_DIRECTORY"))
