# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TipWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TipWindow(object):
    def setupUi(self, TipWindow):
        TipWindow.setObjectName("TipWindow")
        TipWindow.resize(555, 285)
        TipWindow.setMinimumSize(QtCore.QSize(555, 285))
        TipWindow.setMaximumSize(QtCore.QSize(555, 285))
        self.centralwidget = QtWidgets.QWidget(TipWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 80, 391, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 150, 93, 28))
        self.pushButton.setObjectName("pushButton")
        TipWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(TipWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 555, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuOpen = QtWidgets.QMenu(self.menuBar)
        self.menuOpen.setObjectName("menuOpen")
        TipWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(TipWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(TipWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuOpen.addAction(self.actionOpen)
        self.menuOpen.addAction(self.actionClose)
        self.menuBar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(TipWindow)
        QtCore.QMetaObject.connectSlotsByName(TipWindow)

    def retranslateUi(self, TipWindow):
        _translate = QtCore.QCoreApplication.translate
        TipWindow.setWindowTitle(_translate("TipWindow", "PEAnalyzeTool"))
        self.label.setText(_translate("TipWindow", "温馨提示：请打开要分析的PE文件^_^"))
        self.pushButton.setText(_translate("TipWindow", "Exit"))
        self.menuOpen.setTitle(_translate("TipWindow", "File"))
        self.actionOpen.setText(_translate("TipWindow", "Open"))
        self.actionOpen.setShortcut(_translate("TipWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("TipWindow", "Close"))
